// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 002_projects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const checkIfProjectExistByName = `-- name: CheckIfProjectExistByName :one
SELECT EXISTS (Select 1 from projects
where project_name = $1)
`

func (q *Queries) CheckIfProjectExistByName(ctx context.Context, projectName string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkIfProjectExistByName, projectName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkIfProjectExistByUserIdAndName = `-- name: CheckIfProjectExistByUserIdAndName :one
SELECT EXISTS (Select 1 from projects
where creator = $1 and project_name = $2)
`

type CheckIfProjectExistByUserIdAndNameParams struct {
	Creator     uuid.UUID `json:"creator"`
	ProjectName string    `json:"project_name"`
}

func (q *Queries) CheckIfProjectExistByUserIdAndName(ctx context.Context, arg CheckIfProjectExistByUserIdAndNameParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkIfProjectExistByUserIdAndName, arg.Creator, arg.ProjectName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (project_name, created_at, updated_at, creator)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, project_name, created_at, updated_at, creator
`

type CreateProjectParams struct {
	ProjectName string    `json:"project_name"`
	CreatedAt   string    `json:"created_at"`
	UpdatedAt   string    `json:"updated_at"`
	Creator     uuid.UUID `json:"creator"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ProjectName,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Creator,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Creator,
	)
	return i, err
}

const getProjectById = `-- name: GetProjectById :one
SELECT id, project_name, created_at, updated_at, creator FROM projects WHERE id = $1
`

func (q *Queries) GetProjectById(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectById, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Creator,
	)
	return i, err
}

const getProjectByNameAndCreator = `-- name: GetProjectByNameAndCreator :one
SELECT id, project_name, created_at, updated_at, creator FROM projects WHERE project_name = $1 and creator = $2
`

type GetProjectByNameAndCreatorParams struct {
	ProjectName string    `json:"project_name"`
	Creator     uuid.UUID `json:"creator"`
}

func (q *Queries) GetProjectByNameAndCreator(ctx context.Context, arg GetProjectByNameAndCreatorParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByNameAndCreator, arg.ProjectName, arg.Creator)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Creator,
	)
	return i, err
}

const getProjectsByUser = `-- name: GetProjectsByUser :many
SELECT id, project_name, created_at, updated_at, creator FROM projects WHERE creator = $1
`

func (q *Queries) GetProjectsByUser(ctx context.Context, creator uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getProjectsByUser, creator)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.ProjectName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Creator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
