// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type CpePerProject struct {
	ID        string `json:"id"`
	Cpe       string `json:"cpe"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	ProjectID string `json:"project_id"`
}

type CvePerProject struct {
	ID        string `json:"id"`
	Cve       string `json:"cve"`
	Descrip   string `json:"descrip"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	Cpe       string `json:"cpe"`
	Project   string `json:"project"`
	Solved    bool   `json:"solved"`
}

type Project struct {
	ID          *string     `json:"id"`
	ProjectName string      `json:"project_name"`
	CreatedAt   string      `json:"created_at"`
	UpdatedAt   string      `json:"updated_at"`
	Creator     interface{} `json:"creator"`
}

type User struct {
	ID        *string `json:"id"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	Email     string  `json:"email"`
	Hashedp   string  `json:"hashedp"`
}
