name: cd

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: 'write'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      GOFLAGS: -mod=vendor
      GOPROXY: "https://proxy.golang.org,direct"
      
    steps:
      - name: Check out code.
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Go Mod Tidy.
        run: go mod tidy

      - name: Go Mod Vendor.
        run: go mod vendor

      - name: Build app.
        run: ./scripts/buildprod.sh

      - name: 'GCP Auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.WIP_PROVIDER }}'
          service_account: '${{ secrets.SA_GCP }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ./infra


      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: ./infra
#
#      - name: "Connect to GKE"
#        uses: google-github-actions/get-gke-credentials@v2
#        with:
#            cluster_name: ""
##            location: us-central1
 #           project_id: "" #TODO UPDATE AS REQUIRED
#
#      - name: 'Upload image to registry'
#        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-467523/notely-ar-repo/notely:latest . #CORRECT THIS LINE
#
#      - name: Set up Helm
#        uses: azure/setup-helm@v4.3.0
#        with:
#          version: "v3.18.4"
#      
#      - name: Deploy Helm
#        run: |
#          Multi Line HERE 
#      
#      - name: Monitor Deployment
#        run: |
#          Kubectl get deploy -n ${GITHUB_REPOSITORY#*/} --no-headers

      #- name: Deploy to Cloud Run
      #  run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-467523/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-467523 --max-instances=4
